import base64
import json
import os
from functools import lru_cache
from typing import Dict, List, Optional
from urllib.parse import urlencode
from urllib.request import Request, urlopen


SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token"
SPOTIFY_API_URL = "https://api.spotify.com/v1"


def _credentials() -> tuple[Optional[str], Optional[str]]:
    return os.getenv("SPOTIFY_CLIENT_ID"), os.getenv("SPOTIFY_CLIENT_SECRET")


def is_spotify_configured() -> bool:
    client_id, client_secret = _credentials()
    return bool(client_id and client_secret)


def build_authorize_url(redirect_uri: str, state: str = "music-mood") -> Optional[str]:
    client_id, _ = _credentials()
    if not client_id:
        return None

    query = urlencode(
        {
            "client_id": client_id,
            "response_type": "code",
            "redirect_uri": redirect_uri,
            "scope": "playlist-modify-private playlist-modify-public",
            "state": state,
        }
    )
    return f"https://accounts.spotify.com/authorize?{query}"


def exchange_code(code: str, redirect_uri: str) -> Optional[Dict[str, object]]:
    client_id, client_secret = _credentials()
    if not client_id or not client_secret:
        return None

    credentials = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("ascii")
    request = Request(
        SPOTIFY_TOKEN_URL,
        data=urlencode(
            {
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": redirect_uri,
            }
        ).encode("utf-8"),
        headers={
            "Authorization": f"Basic {credentials}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST",
    )

    try:
        with urlopen(request, timeout=5) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception:
        return None


@lru_cache(maxsize=1)
def get_app_access_token() -> Optional[str]:
    client_id, client_secret = _credentials()
    if not client_id or not client_secret:
        return None

    credentials = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("ascii")
    request = Request(
        SPOTIFY_TOKEN_URL,
        data=urlencode({"grant_type": "client_credentials"}).encode("utf-8"),
        headers={
            "Authorization": f"Basic {credentials}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST",
    )

    try:
        with urlopen(request, timeout=5) as response:
            payload = json.loads(response.read().decode("utf-8"))
            return payload.get("access_token")
    except Exception:
        return None


def search_track(title: str, artist: str) -> Optional[Dict[str, str]]:
    token = get_app_access_token()
    if not token:
        return None

    query = urlencode({"q": f'track:"{title}" artist:"{artist}"', "type": "track", "limit": "1"})
    request = Request(
        f"{SPOTIFY_API_URL}/search?{query}",
        headers={"Authorization": f"Bearer {token}"},
    )

    try:
        with urlopen(request, timeout=5) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except Exception:
        return None

    items = payload.get("tracks", {}).get("items", [])
    if not items:
        return None

    track = items[0]
    images = track.get("album", {}).get("images", [])
    return {
        "id": track["id"],
        "title": track["name"],
        "artist": ", ".join(artist_item["name"] for artist_item in track.get("artists", [])),
        "spotifyUrl": track.get("external_urls", {}).get("spotify", ""),
        "coverUrl": images[-1]["url"] if images else "",
        "duration": _format_duration(int(track.get("duration_ms", 0))),
    }


def create_user_playlist(access_token: str, name: str, tracks: List[Dict[str, str]]) -> Optional[Dict[str, str]]:
    user = _spotify_get(access_token, "/me")
    user_id = user.get("id") if user else None
    if not user_id:
        return None

    playlist = _spotify_post(
        access_token,
        f"/users/{user_id}/playlists",
        {"name": name, "public": False, "description": "Generated by Music Mood Matcher"},
    )
    playlist_id = playlist.get("id") if playlist else None
    if not playlist_id:
        return None

    uris = []
    for track in tracks:
        track_id = track.get("id", "")
        if len(track_id) == 22 and not track_id.startswith(("happy-", "sad-", "angry-", "neutral-")):
            uris.append(f"spotify:track:{track_id}")

    if uris:
        _spotify_post(access_token, f"/playlists/{playlist_id}/tracks", {"uris": uris})

    return {
        "id": playlist_id,
        "url": playlist.get("external_urls", {}).get("spotify", ""),
    }


def _spotify_get(access_token: str, path: str) -> Optional[Dict[str, object]]:
    request = Request(
        f"{SPOTIFY_API_URL}{path}",
        headers={"Authorization": f"Bearer {access_token}"},
    )

    try:
        with urlopen(request, timeout=5) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception:
        return None


def _spotify_post(access_token: str, path: str, body: Dict[str, object]) -> Optional[Dict[str, object]]:
    request = Request(
        f"{SPOTIFY_API_URL}{path}",
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urlopen(request, timeout=5) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception:
        return None


def _format_duration(duration_ms: int) -> str:
    total_seconds = max(0, duration_ms // 1000)
    minutes, seconds = divmod(total_seconds, 60)
    return f"{minutes}:{seconds:02d}"


def search_tracks(candidates: List[Dict[str, str]]) -> List[Dict[str, str]]:
    resolved = []
    for candidate in candidates:
        spotify_track = search_track(candidate["title"], candidate["artist"])
        resolved.append({**candidate, **spotify_track} if spotify_track else candidate)
    return resolved
